_test_verbosity = tonumber(arg[1])
print(_test_verbosity)
dofile("basetypes_spec.lua")
dofile("aspect_spec.lua")
dofile("aufgabe1_spec.lua")
dofile("class_spec.lua")
dofile("instance_spec.lua")
dofile("object_spec.lua")